---
Metadata:
  TemplateId: "arn:aws:cloudformation:ap-southeast-2:590183939544:generatedTemplate/a560f4b0-3d27-4368-a581-960a8a076601"
Resources:
  
  # # IAM Policy for CodeArtifact
  IAMManagedPolicy00policycodeartifactnextworkconsumerpolicy008uzsd:
    UpdateReplacePolicy: "Delete"
    Type: "AWS::IAM::ManagedPolicy"
    DeletionPolicy: "Delete"
    DependsOn: "IAMRole00codebuildnextworkwebbuildservicerole00HS6NA"
    Properties:
      ManagedPolicyName: "codeartifact-nextwork-consumer-policy"
      Path: "/"
      Description: "Provides permissions to read from CodeArtifact."
      Groups: []
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Resource: "*"
          Action:
          - "codeartifact:GetAuthorizationToken"
          - "codeartifact:GetRepositoryEndpoint"
          - "codeartifact:ReadFromRepository"
          Effect: "Allow"
        - Condition:
            StringEquals:
              sts:AWSServiceName: "codeartifact.amazonaws.com"
          Resource: "*"
          Action: "sts:GetServiceBearerToken"
          Effect: "Allow"
      Roles:
      - "codebuild-nextwork-web-build-service-role"
      Users: []

  # # IAM Policy for CodeBuild CloudWatch Logs
  IAMManagedPolicy00policyserviceroleCodeBuildCloudWatchLogsPolicynextworkwebbuildapsoutheast200lToqx:
    UpdateReplacePolicy: "Delete"
    Type: "AWS::IAM::ManagedPolicy"
    DeletionPolicy: "Delete"
    DependsOn: "IAMRole00codebuildnextworkwebbuildservicerole00HS6NA"
    Properties:
      ManagedPolicyName: "CodeBuildCloudWatchLogsPolicy-nextwork-web-build-ap-southeast-2"
      Path: "/service-role/"
      Description: "Policy used in trust relationship with CodeBuild"
      Groups: []
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Resource:
          - "arn:aws:logs:ap-southeast-2:590183939544:log-group:nextwork-build-logs"
          - "arn:aws:logs:ap-southeast-2:590183939544:log-group:nextwork-build-logs:*"
          Action:
          - "logs:CreateLogGroup"
          - "logs:CreateLogStream"
          - "logs:PutLogEvents"
          Effect: "Allow"
      Roles:
      - "codebuild-nextwork-web-build-service-role"
      Users: []
  
  # CodeArtifact Local Repository
  CodeArtifactRepository00repositorynextworknextworkpackages00uhdcf:
    UpdateReplacePolicy: "Delete"
    Type: "AWS::CodeArtifact::Repository"
    DeletionPolicy: "Delete"
    Properties: 
      Upstreams:
      - Fn::GetAtt:
        - "CodeArtifactRepository00repositorynextworkmavencentralstore00YuyPT"
        - "Name"
      RepositoryName: "nextwork-packages"
      Description: "Packages for the NextWork web app."
      DomainName:
        Fn::GetAtt:
        - "CodeArtifactDomain00domainnextwork00jZsl8"
        - "Name"

  # S3 Build Artifacts Bucket
  S3Bucket00nextworkbuildartifactseka006oC8Y:    #2
    UpdateReplacePolicy: "Delete"
    Type: "AWS::S3::Bucket"
    DeletionPolicy: "Delete"
    Properties:
      PublicAccessBlockConfiguration:
        RestrictPublicBuckets: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        BlockPublicAcls: true
      BucketName: "nextwork-build-artifacts-eka"
      OwnershipControls:
        Rules:
        - ObjectOwnership: "BucketOwnerEnforced"
      BucketEncryption:
        ServerSideEncryptionConfiguration:
        - BucketKeyEnabled: true
          ServerSideEncryptionByDefault:
            SSEAlgorithm: "AES256"
  
  # # IAM Role for CodeBuild
  IAMRole00codebuildnextworkwebbuildservicerole00HS6NA:  #1
    UpdateReplacePolicy: "Delete"
    Type: "AWS::IAM::Role"
    DeletionPolicy: "Delete"
    Properties:
      Path: "/service-role/"
      # ManagedPolicyArns:
      # - Ref: "IAMManagedPolicy00policycodeartifactnextworkconsumerpolicy008uzsd"
      # - Ref: "IAMManagedPolicy00policyserviceroleCodeBuildBasePolicynextworkwebbuildapsoutheast200jksYo"
      # - Ref: "IAMManagedPolicy00policyserviceroleCodeBuildCloudWatchLogsPolicynextworkwebbuildapsoutheast200lToqx"
      MaxSessionDuration: 3600
      RoleName: "codebuild-nextwork-web-build-service-role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Action: "sts:AssumeRole"
          Effect: "Allow"
          Principal:
            Service: "codebuild.amazonaws.com"

  # # CodeArtifact Upstream Repository
  CodeArtifactRepository00repositorynextworkmavencentralstore00YuyPT:
    UpdateReplacePolicy: "Delete"
    Type: "AWS::CodeArtifact::Repository"
    DeletionPolicy: "Delete"
    Properties:
      RepositoryName: "maven-central-store"
      Description: "Provides Maven artifacts from Maven Central Repository."
      ExternalConnections:
      - "public:maven-central"
      DomainName:
        Fn::GetAtt:
        - "CodeArtifactDomain00domainnextwork00jZsl8"
        - "Name"

  # CodeArtifact Domain
  CodeArtifactDomain00domainnextwork00jZsl8:
    UpdateReplacePolicy: "Delete"
    Type: "AWS::CodeArtifact::Domain"
    DeletionPolicy: "Delete"
    Properties:
      DomainName: "nextwork"

  # IAM Policy for CodeBuild BasePolicy
  IAMManagedPolicy00policyserviceroleCodeBuildBasePolicynextworkwebbuildapsoutheast200jksYo:
    UpdateReplacePolicy: "Delete"
    Type: "AWS::IAM::ManagedPolicy"
    DeletionPolicy: "Delete"
    DependsOn: "IAMRole00codebuildnextworkwebbuildservicerole00HS6NA"
    Properties:
      ManagedPolicyName: "CodeBuildBasePolicy-nextwork-web-build-ap-southeast-2"
      Path: "/service-role/"
      Description: "Policy used in trust relationship with CodeBuild"
      Groups: []
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Resource:
          - "arn:aws:logs:ap-southeast-2:590183939544:log-group:/aws/codebuild/nextwork-web-build"
          - "arn:aws:logs:ap-southeast-2:590183939544:log-group:/aws/codebuild/nextwork-web-build:*"
          Action:
          - "logs:CreateLogGroup"
          - "logs:CreateLogStream"
          - "logs:PutLogEvents"
          Effect: "Allow"
        - Resource:
          - "arn:aws:s3:::codepipeline-ap-southeast-2-*"
          Action:
          - "s3:PutObject"
          - "s3:GetObject"
          - "s3:GetObjectVersion"
          - "s3:GetBucketAcl"
          - "s3:GetBucketLocation"
          Effect: "Allow"
        - Resource:
          - "arn:aws:codecommit:ap-southeast-2:590183939544:nextwork-web-project"
          Action:
          - "codecommit:GitPull"
          Effect: "Allow"
        - Resource:
          - "arn:aws:s3:::nextwork-build-artifacts-eka"
          - "arn:aws:s3:::nextwork-build-artifacts-eka/*"
          Action:
          - "s3:PutObject"
          - "s3:GetBucketAcl"
          - "s3:GetBucketLocation"
          Effect: "Allow"
        - Resource:
          - "arn:aws:codebuild:ap-southeast-2:590183939544:report-group/nextwork-web-build-*"
          Action:
          - "codebuild:CreateReportGroup"
          - "codebuild:CreateReport"
          - "codebuild:UpdateReport"
          - "codebuild:BatchPutTestCases"
          - "codebuild:BatchPutCodeCoverages"
          Effect: "Allow"
      Roles:
      - "codebuild-nextwork-web-build-service-role"
      Users: []

  # CodeCommit Repository
  CodeCommitRepository:
    Type: AWS::CodeCommit::Repository
    Properties:
      RepositoryName: nextwork-web-project
      RepositoryDescription: A web application for the NextWork home page

  # CodeBuild Project
  CodeBuildProject:
    DependsOn: "IAMRole00codebuildnextworkwebbuildservicerole00HS6NA"
    Type: AWS::CodeBuild::Project
    Properties:
      Name: nextwork-web-build
      Description: Build project for NextWork web application
      Source:
        Type: CODECOMMIT
        Location: !GetAtt CodeCommitRepository.CloneUrlHttp
        BuildSpec: buildspec.yml
      Artifacts:
        Type: S3
        Name: nextwork-web-build.zip
        Packaging: ZIP
        Location: !Ref S3Bucket00nextworkbuildartifactseka006oC8Y  #2
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-x86_64-standard:corretto8
      ServiceRole: !GetAtt IAMRole00codebuildnextworkwebbuildservicerole00HS6NA.Arn    #1
      LogsConfig:
        CloudWatchLogs:
          GroupName: nextwork-build-logs
          Status: ENABLED
          StreamName: webapp

